create django project and split settings
OreLana/hotelms pull request #1
Opened 2022-03-02 19:50 UTC by OreLana

# Description
I created the django project and split the settings into dev, production, testing and base settings

# How to Run
- Pull this PR
- Create and activate virtual environment
- Run `python3 manage.py runserver --settings=hotelms.settings.dev`
-

2022-03-02 20:58 UTC, edemaukabi reviewed
Looks good!

2022-03-03 00:08 UTC, eguonoefe requested changes

2022-03-03 00:08 UTC, eguonoefe commented on hotelms/settings/production.py
> +}
Add a new line here at the end of the file

2022-03-03 00:08 UTC, eguonoefe commented on .env.sample
> +PASSWORD=somevalue
Add a new line here at the end of the file

2022-03-03 00:08 UTC, eguonoefe commented on hotelms/settings/base.py
> +# DATABASES = {
Why is this commented. If it's not being used, it should be deleted not commented out

2022-03-03 00:08 UTC, eguonoefe commented on hotelms/settings/testing.py
> +}
Add a new line here at the end of the file

2022-03-03 00:18 UTC, eguonoefe approved these changes

2022-03-03 00:18 UTC, eguonoefe approved these changes
LGTM

2022-03-03 00:33 UTC, merged