CI/CD setup
OreLana/hotelms pull request #3
Opened 2022-03-03 18:19 UTC by Muneerah1612

## I created the workflow for Continuous Integration using GitHub actions, added Procfile to enable deployment to Heroku

P.S: Build will fail, because Secret Key has not been added to GitHub

2022-03-03 21:56 UTC, eguonoefe requested changes

2022-03-03 21:56 UTC, eguonoefe commented on .env.sample
> -PASSWORD=somevalue
Why was this file deleted?

2022-03-03 21:59 UTC, Muneerah1612 commented on .env.sample
> -PASSWORD=somevalue
I thought it was not necessary since we all have our .env file already

2022-03-03 22:00 UTC, eguonoefe commented on .env.sample
> -PASSWORD=somevalue
Okay. So what happens if someone who is new to the project clones the project?

2022-03-03 22:04 UTC, eguonoefe commented on .env.sample
> -PASSWORD=somevalue
How do they know what to put in the .env file?

2022-03-03 22:04 UTC, Muneerah1612 commented on .env.sample
> -PASSWORD=somevalue
Oh, I did not think about that. I will add it back now.

2022-03-03 22:10 UTC, eguonoefe approved these changes
Looks good to me

2022-03-04 19:25 UTC, OreLana approved these changes
Looks good

2022-03-04 19:25 UTC, merged